(() => {
  const css = `
  .site-music-player{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);width:min(430px,calc(100% - 24px));padding:12px 14px;border-radius:18px;background:rgba(15,15,15,.72);border:1px solid rgba(255,255,255,.18);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);box-shadow:0 12px 38px rgba(0,0,0,.35);z-index:9999;color:#fff;font-family:inherit}.site-music-player .mp-title{text-align:center;font-size:13px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.site-music-player .mp-track{text-align:center;font-size:10px;opacity:.62;margin-top:2px}.site-music-player input[type=range]{display:block;width:100%;height:4px;margin:10px 0 0;appearance:none;-webkit-appearance:none;border-radius:20px;background:rgba(255,255,255,.22);outline:none;cursor:pointer}.site-music-player input[type=range]::-webkit-slider-thumb{appearance:none;width:10px;height:10px;border:0;border-radius:50%;background:#fff}.site-music-player input[type=range]::-moz-range-thumb{width:10px;height:10px;border:0;border-radius:50%;background:#fff}.site-music-player .mp-time{display:flex;justify-content:space-between;margin-top:4px;font-size:9px;opacity:.58}.site-music-player .mp-controls{display:flex;align-items:center;justify-content:center;gap:14px;margin-top:9px}.site-music-player button{width:34px;height:34px;border-radius:50%;border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.1);color:#fff;font-size:13px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.2s}.site-music-player button:hover{background:rgba(255,255,255,.22);transform:translateY(-2px)}.site-music-player #mp-play{width:42px;height:42px;font-size:16px;background:rgba(255,255,255,.18)}.site-music-player .mp-status{text-align:center;margin-top:5px;font-size:9px;opacity:.55;min-height:11px}.site-music-player .mp-youtube{position:fixed;width:1px;height:1px;left:-9999px;top:-9999px;opacity:0;pointer-events:none}@media(max-width:480px){.site-music-player{bottom:10px;width:calc(100% - 16px);padding:10px 12px;border-radius:16px}.site-music-player .mp-controls{gap:12px}.site-music-player button{width:32px;height:32px}.site-music-player #mp-play{width:40px;height:40px}.site-music-player .mp-title{font-size:12px}}@media(prefers-reduced-motion:reduce){.site-music-player button{transition:none}}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const box=document.createElement('div');box.className='site-music-player';box.innerHTML=`<div class="mp-title" id="mp-title">Loading music...</div><div class="mp-track" id="mp-track">Playlist loading...</div><input id="mp-progress" type="range" min="0" max="100" step="0.1" value="0"><div class="mp-time"><span id="mp-current">0:00</span><span id="mp-duration">0:00</span></div><div class="mp-controls"><button id="mp-prev" title="Previous">⏮</button><button id="mp-play" title="Play / Pause">▶</button><button id="mp-next" title="Next">⏭</button></div><div class="mp-status" id="mp-status">Connecting...</div><div class="mp-youtube" id="mp-youtube"></div>`;document.body.appendChild(box);
  const PLAYLIST_ID='PLTmtAeNORLyNsvdIKwPuwNoeN0rLiiMq0';let player,timer;
  const $=id=>document.getElementById(id),status=$('mp-status'),progress=$('mp-progress');
  window.onYouTubeIframeAPIReady=function(){player=new YT.Player('mp-youtube',{width:'1',height:'1',playerVars:{listType:'playlist',list:PLAYLIST_ID,controls:0,autoplay:0,playsinline:1,rel:0},events:{onReady,onStateChange,onError}})};
  function onReady(){status.textContent='Loading playlist...';player.loadPlaylist({listType:'playlist',list:PLAYLIST_ID,index:0});let count=0;const check=setInterval(()=>{const list=player.getPlaylist();if(list&&list.length){clearInterval(check);player.setShuffle(true);player.setLoop(true);player.playVideoAt(Math.floor(Math.random()*list.length));status.textContent=`${list.length} songs • Shuffle`}if(++count>20){clearInterval(check);status.textContent='Playlist load failed'}},500)}
  function onStateChange(e){if(e.data===YT.PlayerState.PLAYING){$('mp-play').textContent='⏸';status.textContent='Playing • Shuffle';updateSong();startTimer()}else if(e.data===YT.PlayerState.PAUSED){$('mp-play').textContent='▶';stopTimer();status.textContent='Paused'}else if(e.data===YT.PlayerState.ENDED){player.nextVideo()}else if(e.data===YT.PlayerState.CUED){updateSong()}}
  function updateSong(){const data=player.getVideoData(),list=player.getPlaylist(),index=player.getPlaylistIndex();if(data&&data.title)$('mp-title').textContent=data.title;if(list)$('mp-track').textContent=`Track ${index+1} of ${list.length}`}
  $('mp-play').onclick=()=>{if(!player)return;player.getPlayerState()===YT.PlayerState.PLAYING?player.pauseVideo():player.playVideo()};$('mp-next').onclick=()=>player&&player.nextVideo();$('mp-prev').onclick=()=>{if(!player)return;player.getCurrentTime()>5?player.seekTo(0,true):player.previousVideo()};
  function startTimer(){stopTimer();timer=setInterval(()=>{if(!player)return;const c=player.getCurrentTime(),d=player.getDuration();if(!d)return;progress.value=c/d*100;$('mp-current').textContent=formatTime(c);$('mp-duration').textContent=formatTime(d)},500)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}progress.oninput=()=>{if(player){const d=player.getDuration();if(d)player.seekTo(progress.value/100*d,true)}}function formatTime(s){s=Math.floor(s||0);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}function onError(e){status.textContent='YouTube error: '+e.data}
  if(!document.querySelector('script[src="https://www.youtube.com/iframe_api"]')){const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s)}
})();